export const FIELD_NAMES: { [key: string]: string } = {
    name: 'Название',
    description: 'Описание',
    location: 'Локация',
    type: 'Тип объявления',
    propertyType: 'Тип недвижимости',
    area: 'Площадь',
    rooms: 'Количество комнат',
    price: 'Цена',
    brand: 'Марка',
    model: 'Модель',
    year: 'Год выпуска',
    mileage: 'Пробег',
    serviceType: 'Тип услуги',
    experience: 'Опыт',
    cost: 'Стоимость',
    workSchedule: 'График работы',
};