version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    networks:
      - app-network

  front:
    build:
      context: ./front
    ports:
      - "3001:3001"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
